### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr-tester#2]
@as-com any idea why it fails http://jsdelivr-testing.aws.af.cm/runTests.php?host=origin.jsdelivr.net with 3 missmatches? They should be the same

**Comment by as-com** [comment]
Did you recently modify the behavior of the /g/ script? I think you might have changed the way it adds whitespace in between files?

**Comment by jimaek** [comment]
I purged the failing files from the CDNs, if that was the problem then it should have been fixed but it didnt

P.S. Can you replace /mathjax/latest/MathJax.js with some other project?

**Comment by as-com** [comment]
I’m going to update the hashes for the failing files. I suspect it’s something about the files being modified or a slight change in the script’s behavior.




MathJax was randomly selected for the dynamic testing. It will change when you reload the page.

**Comment by as-com** [comment]
The issue should be fixed now.

**Comment by jimaek** [comment]
awesome, thanks
